os:
    - windows
language: node_js
node_js:
    - "13"
install:
    - travis_retry npm ci
    - npm run build
    - npm run prebuilds
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
